# Node docker image on which this would be run
image: node:latest

cache:
  paths: 
    - node_modules/

# Pipeline:
stages:
  - install
  - build
  - deploy

# Jobs:

install_dependencies:
      stage: install
      script:
        - npm install

bundle:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
     - dist/

deploy-staging:
  stage: deploy
  script:
    - npm ci:deploy:staging
  only:
    - develop

deploy-production:
  stage: deploy
  script:
    - npm ci:deploy:prod
  only:
    - master