# Node docker image on which this would be run
image: node:latest

cache:
  paths: 
    - node_modules/

# Pipeline:
stages:
  - install
  - build
  - test
  - deploy

# Jobs:

install_dependencies:
      stage: install
      script:
        - npm install

bundle:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
     - dist/

deploy_staging:
  only:
    - develop
    - master
  stage: deploy
  script:
    - npm install -g now
    - now --token=$PND_TOKEN
    - ./node_modules/.bin/now -e NODE_ENV=staging --regions sfo --scale 1 --token=$PND_TOKEN
    - ./node_modules/.bin/now alias pickup-n-dropoff.com --token=MY TOKEN
    