# Node docker image on which this would be run
image: node:latest

cache:
  paths: 
    - node_modules/

# Pipeline:
stages:
  - install
  - build
  - test
  - deploy

# Jobs:

install_dependencies:
      stage: install
      script:
        - npm install

bundle:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
     - dist/

deploy_staging:
  only:
    - develop
    - master
  stage: deploy
  before_script:
    npm install -g now
  script:
    now deploy --token $PND_TOKEN
